[package]
name = "snapshift"
version = "0.1.6"
description = "SnapShift - Image converter"
authors = ["Miro"]
edition = "2021"

[lib]
name = "snapshift_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "macos-private-api"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
dirs = "5"
chrono = "0.4"
rayon = "1.10"
image = { version = "0.25", features = ["jpeg", "png", "webp", "tiff"] }
tempfile = "3"
thiserror = "2"
log = "0.4"
env_logger = "0.11"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
serde_json = "1.0.150"

[target.'cfg(target_os = "linux")'.dependencies]
libheif-rs = { version = "1.1", features = ["compile-libheif"] }

[target.'cfg(target_os = "windows")'.dependencies]
libheif-rs = { version = "1.1" }
